services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  ml-client:
    build: ./machine-learning-client
    container_name: ml-client
    depends_on:
      - mongodb
    networks:
      - app-network

  web-app:
    build: ./web-app
    container_name: web-app
    ports:
      - "5000:5000" # Exposes Flask app to host
    depends_on:
      - mongodb
      - ml-client
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - ML_SERVICE_URL=http://ml-client:5001 

networks:
  app-network:
    driver: bridge
