name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [machine-learning-client, web-app]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug directory structure
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache CUDA
      uses: actions/cache@v3
      with:
        path: /usr/local/cuda
        key: ${{ runner.os }}-cuda-toolkit-12-2
        restore-keys: |
          ${{ runner.os }}-cuda-toolkit-

    - name: Install CUDA (for ML only)
      if: ${{ matrix.service == 'machine-learning-client' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends wget gnupg
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
        wget https://developer.download.nvidia.com/compute/cuda/12.6.2/local_installers/cuda-repo-ubuntu2204-12-6-local_12.6.2-560.35.03-1_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu2204-12-6-local_12.6.2-560.35.03-1_amd64.deb
        sudo cp /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-12-6

    - name: Install cuDNN
      if: ${{ matrix.service == 'machine-learning-client' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends wget
        wget https://developer.download.nvidia.com/compute/redist/cudnn/v8.9.5/cudnn-linux-x86_64-8.9.5.29_cuda12-archive.tar.xz
        tar -xvf cudnn-linux-x86_64-8.9.5.29_cuda12-archive.tar.xz
        sudo cp cudnn-linux-x86_64-8.9.5.29_cuda12-archive/include/* /usr/local/cuda/include/
        sudo cp cudnn-linux-x86_64-8.9.5.29_cuda12-archive/lib/* /usr/local/cuda/lib64/
        sudo chmod a+r /usr/local/cuda/include/cudnn*.h /usr/local/cuda/lib64/libcudnn*

    - name: Install dependencies
      working-directory: ${{ matrix.service }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev

    - name: Run linting
      working-directory: ${{ matrix.service }}
      run: |
        if [ "${{ matrix.service }}" == "machine-learning-client" ]; then
          [ -f src/main.py ] && pipenv run pylint src/main.py || echo "src/main.py not found"
        elif [ "${{ matrix.service }}" == "web-app" ]; then
          [ -f app.py ] && pipenv run pylint app.py || echo "app.py not found"
        fi

    - name: Format code with Black
      working-directory: ${{ matrix.service }}
      run: pipenv run black --check .

    - name: Run tests
      working-directory: ${{ matrix.service }}
      run: pipenv run pytest
