name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [machine-learning-client, web-app]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug directory structure
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache CUDA
      uses: actions/cache@v3
      with:
        path: /usr/local/cuda
        key: ${{ runner.os }}-cuda-toolkit-12-2
        restore-keys: |
          ${{ runner.os }}-cuda-toolkit-

    - name: Install dependencies
      working-directory: ${{ matrix.service }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev

    - name: Run linting
      working-directory: ${{ matrix.service }}
      run: |
        if [ "${{ matrix.service }}" == "machine-learning-client" ]; then
          [ -f src/main.py ] && pipenv run pylint src/main.py || echo "src/main.py not found"
        elif [ "${{ matrix.service }}" == "web-app" ]; then
          [ -f app.py ] && pipenv run pylint app.py || echo "app.py not found"
        fi

    - name: Format code with Black
      working-directory: ${{ matrix.service }}
      run: pipenv run black --check .

    - name: Run tests
      working-directory: ${{ matrix.service }}
      run: pipenv run pytest
