name: Machine Learning Client CI

on:
  push:
    branches:
      - main
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client.yml'

  pull_request:
    paths:
      - 'machine-learning-client/**'
      - '.github/workflows/ml-client.yml'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./machine-learning-client

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install CUDA Toolkit
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
          sudo apt-get update
          sudo apt-get install -y cuda libcudnn8 libcudnn8-dev

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run tests
        run: |
          pipenv run coverage run -m pytest
          pipenv run coverage report -i

      - name: Build Docker image
        run: |
          docker build -t ml-client .
