name: Web App CI

on:
  push:
    branches:
      - main
    paths:
      - 'web_app/**'
      - '.github/workflows/web-app.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'web_app/**'
      - '.github/workflows/web-app.yml'

jobs:
  test-web-app:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    env:
      LANG: en_US.UTF-8
      MONGO_URI: mongodb://localhost:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install pipenv and dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --python $(which python3.11)

      - name: Run tests
        run: |
          pipenv run pytest --cov=web_app --cov-report=xml --cov-report=term test_app.py
        env:
          MONGO_URI: mongodb://localhost:27017

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
